// GENERATED by scripts/build-bible.mjs — do not edit by hand.
// Source: am-2000 (90 books, EOTC 81-book canon, LXX psalm numbering).

/** Chapter counts per book number (index 0 = book 1). */
export const CHAPTER_COUNTS: readonly number[] = [
  50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 11, 42, 151, 24, 12, 8, 66, 52, 5, 48, 14, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22, 14, 16, 19, 51, 5, 1, 36, 21, 13, 10, 9, 6, 34, 42, 1, 1, 72, 43, 12, 1, 1, 1, 1, 5,
];

/** Book count in the bundled edition. */
export const BOOK_COUNT = 90;

/**
 * Books the consecutive reading plan walks. Held at 66 so the through-the-Bible
 * plan stays the familiar canon; the deuterocanonical books (67-90) are
 * readable and searchable but not auto-scheduled.
 */
export const PLAN_BOOK_COUNT = 66;
export const PLAN_TOTAL_CHAPTERS = 1186;

/** Book number -> canonical id, for joining against bible81 / lectionary data. */
export const BOOK_IDS: readonly string[] = [
  'GEN', 'EXO', 'LEV', 'NUM', 'DEU', 'JOS', 'JDG', 'RUT', '1SA', '2SA', '1KI', '2KI', '1CH', '2CH', 'EZR', 'NEH', 'EST', 'JOB', 'PSA', 'PRO', 'ECC', 'SNG', 'ISA', 'JER', 'LAM', 'EZK', 'DAN', 'HOS', 'JOL', 'AMO', 'OBA', 'JON', 'MIC', 'NAM', 'HAB', 'ZEP', 'HAG', 'ZEC', 'MAL', 'MAT', 'MRK', 'LUK', 'JHN', 'ACT', 'ROM', '1CO', '2CO', 'GAL', 'EPH', 'PHP', 'COL', '1TH', '2TH', '1TI', '2TI', 'TIT', 'PHM', 'HEB', 'JAS', '1PE', '2PE', '1JN', '2JN', '3JN', 'JUD', 'REV', 'TOB', 'JDT', 'WIS', 'SIR', 'BAR', 'LJE', '1MA', '2MA', '1ES', '3MA', '2ES', '4MA', 'JUB', 'ENO', 'OTH', 'XXG', 'XXA', 'XXC', 'XXB', 'XXD', 'XXE', 'XXF', 'LAO', '1BA',
];

/** Book number -> Amharic name. */
export const BOOK_NAMES: readonly string[] = [
  "ኦሪት ዘፍጥረት",
  "ኦሪት ዘጸአት",
  "ኦሪት ዘሌዋውያን",
  "ኦሪት ዘኊልቊ",
  "ኦሪት ዘዳግም",
  "መጽሐፈ ኢያሱ ወልደ ነዌ",
  "መጽሐፈ መሳፍንት",
  "መጽሐፈ ሩት",
  "መጽሐፈ ሳሙኤል ቀዳማዊ",
  "መጽሐፈ ሳሙኤል ካልዕ",
  "መጽሐፈ ነገሥት ቀዳማዊ",
  "መጽሐፈ ነገሥት ካልዕ",
  "መጽሐፈ ዜና መዋዕል ቀዳማዊ",
  "መጽሐፈ ዜና መዋዕል ካልዕ",
  "መጽሐፈ ዕዝራ",
  "መጽሐፈ ነህምያ",
  "መጽሐፈ አስቴር",
  "መጽሐፈ ኢዮብ",
  "መዝሙረ ዳዊት",
  "መጽሐፈ ምሳሌ",
  "መጽሐፈ መክብብ",
  "መኃልየ መኃልይ ዘሰሎሞን",
  "ትንቢተ ኢሳይያስ",
  "ትንቢተ ኤርምያስ",
  "ሰቆቃወ ኤርምያስ",
  "ትንቢተ ሕዝቅኤል",
  "ትንቢተ ዳንኤል",
  "ትንቢተ ሆሴዕ",
  "ትንቢተ ኢዩኤል",
  "ትንቢተ አሞጽ",
  "ትንቢተ አብድዩ",
  "ትንቢተ ዮናስ",
  "ትንቢተ ሚክያስ",
  "ትንቢተ ናሆም",
  "ትንቢተ ዕንባቆም",
  "ትንቢተ ሶፎንያስ",
  "ትንቢተ ሐጌ",
  "ትንቢተ ዘካርያስ",
  "ትንቢተ ሚልክያስ",
  "የማቴዎስ ወንጌል",
  "የማርቆስ ወንጌል",
  "የሉቃስ ወንጌል",
  "የዮሐንስ ወንጌል",
  "የሐዋርያት ሥራ",
  "ወደ ሮሜ ሰዎች",
  "1ኛ ወደ ቆሮንቶስ ሰዎች",
  "2ኛ ወደ ቆሮንቶስ ሰዎች",
  "ወደ ገላትያ ሰዎች",
  "ወደ ኤፌሶን ሰዎች",
  "ወደ ፊልጵስዩስ ሰዎች",
  "ወደ ቆላስይስ ሰዎች",
  "1ኛ ወደ ተሰሎንቄ ሰዎች",
  "2ኛ ወደ ተሰሎንቄ ሰዎች",
  "1ኛ ወደ ጢሞቴዎስ",
  "2ኛ ወደ ጢሞቴዎስ",
  "ወደ ቲቶ",
  "ወደ ፊልሞና",
  "ወደ ዕብራውያን",
  "የያዕቆብ መልእክት",
  "1ኛ የጴጥሮስ መልእክት",
  "2ኛ የጴጥሮስ መልእክት",
  "1ኛ የዮሐንስ መልእክት",
  "2ኛ የዮሐንስ መልእክት",
  "3ኛ የዮሐንስ መልእክት",
  "የይሁዳ መልእክት",
  "የዮሐንስ ራዕይ",
  "መጽሐፈ ጦቢት",
  "መጽሐፈ ዮዲት",
  "መጽሐፈ ጥበብ",
  "መጽሐፈ ሲራክ",
  "ተረፈ ባሮክ",
  "ተረፈ ኤርምያስ",
  "መጽሐፈ መቃብያን ቀዳማዊ",
  "መጽሐፈ መቃብያን ካልእ",
  "መጽሐፈ ዕዝራ ሱቱኤል",
  "መጽሐፈ መቃብያን ሣልስ",
  "መጽሐፈ ዕዝራ ካልዕ",
  "መጽሐፈ ተግሣጽ",
  "መጽሐፈ ኩፋሌ",
  "መጽሐፈ ሄኖክ",
  "መጽሐፈ ኪዳን ቀዳማዊ",
  "መጽሐፈ ሥርዓተ ጽዮን",
  "መጽሐፈ ዮሴፍ ወልደ ኮርዮን",
  "መጽሐፈ ዲድስቅልያ",
  "መጽሐፈ ቀሌምንጦስ",
  "መጽሐፈ ትእዛዝ",
  "መጽሐፈ አብጥሊስ",
  "መጽሐፈ ግጽው",
  "መጽሐፈ ኪዳን ካልዕ",
  "መጽሐፈ ባሮክ",
];
