// Pure, server-free helpers for the consecutive daily-chapter reading plan.
// Imported by BOTH the server module readingPlan.ts and the client component
// SettingsClient.tsx, so it must NOT import any server-only code (next/headers).
// Kept byte-for-byte identical in behaviour to the Flutter app (daily.dart).

export type Pick = { book: number; chapter: number };

// Chapter counts come from the bundled edition (generated by
// scripts/build-bible.mjs) so they can never drift from the JSON on disk.
export {
  CHAPTER_COUNTS,
  BOOK_COUNT,
  PLAN_BOOK_COUNT,
} from "@/lib/bibleCanon";
import {
  CHAPTER_COUNTS,
  PLAN_BOOK_COUNT,
  PLAN_TOTAL_CHAPTERS,
} from "@/lib/bibleCanon";

export const TOTAL_CHAPTERS = PLAN_TOTAL_CHAPTERS;

/** 0-based position of a (1-based book, 1-based chapter) in the linear walk. */
export function linearIndex(book: number, chapter: number): number {
  let sum = 0;
  for (let i = 0; i <= book - 2; i++) sum += CHAPTER_COUNTS[i];
  return sum + (chapter - 1);
}

/** Convert a 0-based linear index back to {book, chapter} (both 1-based). */
export function chapterFromIndex(idx: number): Pick {
  let rem = idx;
  for (let i = 0; i < PLAN_BOOK_COUNT; i++) {
    if (rem < CHAPTER_COUNTS[i]) return { book: i + 1, chapter: rem + 1 };
    rem -= CHAPTER_COUNTS[i];
  }
  return { book: PLAN_BOOK_COUNT, chapter: CHAPTER_COUNTS[PLAN_BOOK_COUNT - 1] };
}

/** Whole days from `start` to `today` (both YYYY-MM-DD), never negative. */
export function daysBetween(start: string, today: string): number {
  const s = Date.parse(`${start}T00:00:00Z`);
  const t = Date.parse(`${today}T00:00:00Z`);
  if (Number.isNaN(s) || Number.isNaN(t)) return 0;
  return Math.max(0, Math.floor((t - s) / 86400000));
}

/** The consecutive-plan chapter for `today`, given the user's start point. */
export function consecutivePick(
  startBook: number,
  startChapter: number,
  startDate: string,
  today: string,
): Pick {
  const book = Math.min(Math.max(1, startBook), PLAN_BOOK_COUNT);
  const chapter = Math.min(Math.max(1, startChapter), CHAPTER_COUNTS[book - 1]);
  const daysElapsed = daysBetween(startDate, today);
  const idx = (linearIndex(book, chapter) + daysElapsed) % TOTAL_CHAPTERS;
  return chapterFromIndex(idx);
}
