// GENERATED by web/scripts/build-bible.mjs — do not edit by hand.
// Mirrors web/src/lib/bibleCanon.ts. Source: am-2000, EOTC 81-book canon.

/// Chapters per book (index 0 = book 1). Must stay identical to the web app's
/// CHAPTER_COUNTS so the "read in order" plan picks the SAME chapter on both.
const chapterCounts = [
  50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 11, 42, 151, 24, 12, 8, 66, 52, 5, 48, 14, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22, 14, 16, 19, 51, 5, 1, 36, 21, 13, 10, 9, 6, 34, 42, 1, 1, 72, 43, 12, 1, 1, 1, 1, 5,
];

/// Books in the bundled edition.
const bookCount = 90;

/// Books the consecutive reading plan walks (see bibleCanon.ts).
const planBookCount = 66;

/// Sum of chapterCounts over the first [planBookCount] books.
const chapterTotal = 1186;

/// Book number -> canonical id.
const bookIds = [
  'GEN', 'EXO', 'LEV', 'NUM', 'DEU', 'JOS', 'JDG', 'RUT', '1SA', '2SA', '1KI', '2KI', '1CH', '2CH', 'EZR', 'NEH', 'EST', 'JOB', 'PSA', 'PRO', 'ECC', 'SNG', 'ISA', 'JER', 'LAM', 'EZK', 'DAN', 'HOS', 'JOL', 'AMO', 'OBA', 'JON', 'MIC', 'NAM', 'HAB', 'ZEP', 'HAG', 'ZEC', 'MAL', 'MAT', 'MRK', 'LUK', 'JHN', 'ACT', 'ROM', '1CO', '2CO', 'GAL', 'EPH', 'PHP', 'COL', '1TH', '2TH', '1TI', '2TI', 'TIT', 'PHM', 'HEB', 'JAS', '1PE', '2PE', '1JN', '2JN', '3JN', 'JUD', 'REV', 'TOB', 'JDT', 'WIS', 'SIR', 'BAR', 'LJE', '1MA', '2MA', '1ES', '3MA', '2ES', '4MA', 'JUB', 'ENO', 'OTH', 'XXG', 'XXA', 'XXC', 'XXB', 'XXD', 'XXE', 'XXF', 'LAO', '1BA',
];
